# Generated by Django 5.1 on 2024-08-26 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sobre_tituloUm', models.CharField(max_length=200)),
                ('Sobre_paragrafoUm', models.TextField(max_length=400)),
                ('Sobre_tituloDois', models.CharField(max_length=200)),
                ('Sobre_paragrafoDois', models.TextField(max_length=400)),
                ('Sobre_imagem', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Beneficios_imagem', models.CharField(max_length=255)),
                ('Beneficios_descricao', models.TextField(max_length=100)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Media_mensal', models.CharField(max_length=100)),
                ('Valor_consumo', models.CharField(max_length=100)),
                ('Kwp', models.CharField(max_length=100)),
                ('Area_placas', models.CharField(max_length=100)),
                ('Custo', models.CharField(max_length=100)),
                ('Parcelas_mensais', models.CharField(max_length=100)),
                ('Parcela_fixa', models.CharField(max_length=100)),
                ('Valor_mensal', models.CharField(max_length=100)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Cargo', models.CharField(max_length=255)),
                ('Texto_depoimento', models.TextField(max_length=400)),
                ('Depoimento_imagem', models.CharField(max_length=255)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_projeto', models.CharField(max_length=400)),
                ('Cidade', models.CharField(max_length=255)),
                ('Imagens', models.TextField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
